# This file is primarily used to configure Ruff.
# Ruff is the formatter and linter that we use in this codebase for all of our Python code.

# If you would like to read more about Ruff configuration then please see the following: https://docs.astral.sh/ruff/configuration

# top level
indent-width      = 4
line-length       = 130
respect-gitignore = true

[lint.pydocstyle]
convention = "numpy"

[lint.pylint]
max-positional-args = 8
max-returns         = 10
max-locals          = 30

[lint.isort]
combine-as-imports     = true
order-by-type          = true
relative-imports-order = "furthest-to-closest"

# Ruff will place the import sections in this order:
section-order = [
    "future",
    "standard-library",
    "third-party",
    "qtpy",
    "ros",
    "first-party",
    "local-folder",
]

# A list of modules to consider standard-library, in addition to those known to Ruff in advance.
extra-standard-library = []

# A list of modules to consider first-party, regardless of whether they can be identified as such via introspection of the local filesystem.
known-first-party = [
    "ground_station",
    "utils",
    "widgets",
    "map_widget",
    "autoboat_launch",
    "autoboat_msgs",
    "autopilot",
    "autopilot_cpp",
    "drivers",
    "drivers_cpp",
    "object_detection",
    "old_sailboat_simulation",
    "custom_lift_drag",
    "foil_dynamics",
    "sail_limits",
    "simulation_camera_engine",
    "simulation_models",
    "simulation_transform",
    "wind_arrow",
]

[lint.isort.sections]
qtpy = ["qtpy", "pyqtgraph"]
ros = [
    "rclpy",
    "rosidl_runtime_py",
    "ament_index_python",
    "ament_index_python.packages",
    "ament_copyright",
    "ament_flake8",
    "ament_pep257",
    "std_msgs",
    "geometry_msgs",
    "sensor_msgs",
    "nav_msgs",
    "cv_bridge",
    "launch",
    "launch_ros",
]

[lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
future-annotations = true
logger-objects     = ["rclpy.impl.rcutils_logger.RcutilsLogger"]

select    = ["ALL"]
unfixable = ["F401"]


# Here are all of the linting rules to ignore
ignore = [
    "ANN401",
    "BLE001",
    "COM812",
    "CPY001",
    "D212",
    "D404",
    "DOC501",
    "DOC502",
    "S101",
    "S113",
    "S311",
    "SIM115",
    "SLF001",
    "INP001",
    "D100",
    "D101",
    "D103",
    "D107",
    "D202",
    "D205",
    "D401",
    "C901",
    "E401",
    "E303",
    "E741",
    "EM101",
    "ERA001",
    "EXE002",
    "EM102",
    "F403",
    "F405",
    "FBT001",
    "FBT002",
    "FBT003",
    "N802",
    "N813",
    "PIE790",
    "PLC2801",
    "PLR0904",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLR6201",
    "PLR6301",
    "PERF203",
    "PERF401",
    "PTH",
    "T201",
    "TD002",
    "TD003",
    "TC001",
    "TC002",
    "TC003",
    "TRY002",
    "TRY003",
    "TRY301",
    "TRY400",
    "RET505",
    "RUF023",
    "G004",
    "UP015",
    "W293",
    "Q000",
    "UP045",
    "SIM108",
]
