FROM vtautoboat/autoboat_docker_dev_image:yolo

ARG USERNAME=autoboat_user
USER $USERNAME

RUN mkdir -p /tmp/autoboat_scripts

COPY .devcontainer/devcontainer_variants/install_deepstream_helper_script.sh /tmp/autoboat_scripts/install_deepstream_helper_script.sh
RUN bash /tmp/autoboat_scripts/install_deepstream_helper_script.sh


COPY src/object_detection/object_detection/deepstream_yolo/ /tmp/deepstream_yolo

# Compile the deepstream_yolo library
RUN cd /tmp/deepstream_yolo/ \
    && export CUDA_VER=12.6 \
    && make -C nvdsinfer_custom_impl_Yolo clean && make -C nvdsinfer_custom_impl_Yolo \
    && gst-inspect-1.0 > /dev/null # initialize gstreamer plugins


RUN echo "export DEVCONTAINER_VARIANT=deepstream_and_yolo" >> ~/.bashrc


CMD ["/bin/bash"]
