FROM vtautoboat/development_image:latest

ARG USERNAME=autoboat_user
USER $USERNAME

RUN mkdir -p /tmp/autoboat_scripts


COPY --chown=${USERNAME}:${USERNAME} .devcontainer/devcontainer_variants/install_deepstream_helper_script.sh /tmp/autoboat_scripts/install_deepstream_helper_script.sh
# COPY .devcontainer/devcontainer_variants/install_deepstream_helper_script.sh /tmp/autoboat_scripts/install_deepstream_helper_script.sh

RUN bash /tmp/autoboat_scripts/install_deepstream_helper_script.sh


# Compile the deepstream_yolo library
# COPY src/object_detection/object_detection/deepstream_yolo/ /tmp/deepstream_yolo
COPY --chown=${USERNAME}:${USERNAME} src/object_detection/object_detection/cv_library/ /tmp/cv_library
RUN cd /tmp/cv_library/ \
    && export CUDA_VER=12.6 \
    && make -C deepstream_yolo_library clean && make -C deepstream_yolo_library \
    && gst-inspect-1.0 > /dev/null # initialize gstreamer plugins



RUN echo "export DEVCONTAINER_VARIANT=deepstream" >> ~/.bashrc

CMD ["/bin/bash"]