# Contains a bunch of statistics about the jetson like power, temperature, cpu usage etc that we might be interested in

float32 cpu_temperature_celcius
float32 gpu_temperature_celcius
float32 soc_temperature_celcius

float32 soc_power_usage_watts
float32 total_power_usage_watts
float32 max_power_usage_watts

float32 cpu_utilization_percent
float32 gpu_utilization_percent
float32 ram_utilization_percent


